#!/usr/bin/env php
<?php
declare(strict_types=1);


use TYPO3\CMS\Core\Context\DateTimeAspect;
use TYPO3\CMS\Core\Core\Bootstrap;
use TYPO3\CMS\Core\Core\SystemEnvironmentBuilder;
use TYPO3\CMS\Core\Database\Connection;
use TYPO3\CMS\Core\Database\ConnectionPool;
use TYPO3\CMS\Core\Database\Query\QueryBuilder;
use TYPO3\CMS\Core\Database\Query\Restriction\DeletedRestriction;
use TYPO3\CMS\Core\Database\Query\Restriction\FrontendWorkspaceRestriction;
use TYPO3\CMS\Core\Utility\GeneralUtility;
use TYPO3\CMS\Frontend\Http\Application;
use TYPO3\CMS\Redirects\Service\SlugService;

(static function() {
    $classLoader = require __DIR__.'/../../vendor/autoload.php';
    SystemEnvironmentBuilder::run(0, SystemEnvironmentBuilder::REQUESTTYPE_FE);
    Bootstrap::init($classLoader)->get(Application::class);

    if(!file_exists('redirects.csv')) {
        die('Missing redirects.csv in /app!');
    }

    /** @var ConnectionPool $connection */
    $connection = GeneralUtility::makeInstance(ConnectionPool::class);
    $pagesQueryBuilder = $connection->getQueryBuilderForTable('pages');
    $pagesQueryBuilder
        ->getRestrictions()
        ->removeAll()
        ->add(GeneralUtility::makeInstance(DeletedRestriction::class))
        ->add(GeneralUtility::makeInstance(FrontendWorkspaceRestriction::class));

    $handle = fopen('redirects.csv', 'rb');
    while ( ($data = fgetcsv($handle, 0, ';') ) !== FALSE ) {
        $originalUrl = parse_url(trim($data[0]));

        $pagesQueryBuilder->resetQueryPart('where');
        $statement = $pagesQueryBuilder->select('uid')
            ->from('pages')
            ->andWhere($pagesQueryBuilder->expr()->eq(
                'slug',
                $pagesQueryBuilder->createNamedParameter(trim($data[1])), PDO::PARAM_STR
            ))
            ->execute();

        if ($statement->rowCount() === 0) {
            file_put_contents('redirects-report.txt', sprintf(
                'Error: Redirect %s to %s. No matching TYPO3 page found' . PHP_EOL,
                $data[0],
                $data[1]
            ));
            continue;
        }

        if (!isset($originalUrl['path'])) {
            die(sprintf('Unable to parse %s', $data[0]));
        }

        $target = sprintf('t3://page?uid=%d', $statement->fetchColumn(0));

        /** @var DateTimeAspect $date */
        $record = [
            'pid' => 0,
            'updatedon' => time(),
            'createdon' => time(),
            'createdby' => 1,
            'deleted' => 0,
            'disabled' => 0,
            'starttime' => 0,
            'endtime' => 0,
            'source_host' => $originalUrl['host'] ?? '*',
            'source_path' => $originalUrl['path'],
            'is_regexp' => 0,
            'force_https' => 0,
            'respect_query_parameters' => 0,
            'target' => $target,
            'target_statuscode' => 301,
            'hitcount' => 0,
            'lasthiton' => 0,
            'disable_hitcount' => 0,
        ];
        $connection = GeneralUtility::makeInstance(ConnectionPool::class)
            ->getConnectionForTable('sys_redirect');
        $connection->insert('sys_redirect', $record);

        printf('Add redirect: %s => %s (%s)' . PHP_EOL, $data[0], $data[1], $target);
    }

})();
